"""Win/loss analysis: where you win, where you lose, and why, as a single-file HTML dashboard."""

from __future__ import annotations

import csv
import html
from collections import Counter, defaultdict
from pathlib import Path


def load(path: str | Path) -> list[dict]:
    with open(path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    for r in rows:
        r["won"] = r["outcome"].strip().lower() == "won"
        r["amount"] = float(r.get("amount") or 0)
    return rows


def rate(rows: list[dict]) -> float:
    return sum(r["won"] for r in rows) / len(rows) if rows else 0.0


def by(rows: list[dict], key: str) -> list[tuple[str, int, float]]:
    g: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        g[r[key]].append(r)
    return sorted(((k, len(v), rate(v)) for k, v in g.items()), key=lambda x: -x[1])


def loss_reasons(rows: list[dict]) -> list[tuple[str, int]]:
    return Counter(r["reason"] for r in rows if not r["won"]).most_common()


def insights(rows: list[dict]) -> list[str]:
    """Plain-language findings a PM can take into a roadmap review."""
    out, base = [], rate(rows)
    for key in ("segment", "competitor"):
        for name, n, wr in by(rows, key):
            if n >= 5 and abs(wr - base) >= 0.12:
                out.append(f"{'Strong' if wr > base else 'Weak'} against {name} ({key}): {wr:.0%} win rate vs {base:.0%} overall, {n} deals.")
    reasons = loss_reasons(rows)
    if reasons:
        top, n = reasons[0]
        share = n / sum(c for _, c in reasons)
        out.append(f"Top loss reason is '{top}', behind {share:.0%} of losses. That's the first roadmap conversation.")
    return out


def _bars(items: list[tuple[str, float]], fmt, color: str, width: int = 520) -> str:
    h, row = 26, 34
    svg = [f'<svg viewBox="0 0 {width} {row * len(items) + 6}" role="img">']
    mx = max((v for _, v in items), default=1) or 1
    for i, (k, v) in enumerate(items):
        y, w = i * row, (width - 190) * v / mx
        svg.append(f'<text x="0" y="{y + 18}" class="k">{html.escape(k)}</text><rect x="150" y="{y + 2}" width="{w:.1f}" height="{h}" rx="3" fill="{color}"/><text x="{156 + w:.1f}" y="{y + 20}" class="v">{fmt(v)}</text>')
    return "".join(svg) + "</svg>"


def dashboard(rows: list[dict], title: str = "Win/loss") -> str:
    won = [r for r in rows if r["won"]]
    kpis = [("Win rate", f"{rate(rows):.0%}"), ("Deals", f"{len(rows)}"), ("Won revenue", f"${sum(r['amount'] for r in won):,.0f}"),
            ("Avg won deal", f"${(sum(r['amount'] for r in won) / len(won) if won else 0):,.0f}")]
    seg = _bars([(k, wr) for k, _, wr in by(rows, "segment")], lambda v: f"{v:.0%}", "#3455FA")
    comp = _bars([(k, wr) for k, _, wr in by(rows, "competitor")], lambda v: f"{v:.0%}", "#0E0E10")
    rea = _bars([(k, float(n)) for k, n in loss_reasons(rows)], lambda v: f"{v:.0f}", "#FF6B4A")
    ins = "".join(f"<li>{html.escape(i)}</li>" for i in insights(rows))
    k = "".join(f"<div class='kpi'><span>{a}</span><b>{b}</b></div>" for a, b in kpis)
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)}</title>
<style>body{{margin:0;background:#F4F4F2;color:#0E0E10;font:15px/1.5 system-ui,sans-serif}}main{{max-width:1080px;margin:0 auto;padding:40px 20px}}
h1{{font:400 40px Georgia,serif;margin:0 0 4px}}.sub{{color:#6B6B72;margin:0 0 28px}}.kpis{{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}}
.kpi,.card{{background:#fff;border:1px solid #E4E4E0;padding:18px}}.kpi span{{display:block;font:12px ui-monospace,monospace;color:#6B6B72;text-transform:uppercase;letter-spacing:.06em}}.kpi b{{font:400 34px Georgia,serif}}
.grid{{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}}h2{{font:12px ui-monospace,monospace;text-transform:uppercase;letter-spacing:.08em;color:#6B6B72;margin:0 0 12px}}
svg{{width:100%;height:auto}}svg .k{{font-size:13px;fill:#0E0E10}}svg .v{{font-size:12px;fill:#54545B;font-family:ui-monospace,monospace}}ul{{margin:0;padding-left:18px}}li{{margin:6px 0}}
@media(max-width:760px){{.kpis,.grid{{grid-template-columns:1fr 1fr}}.grid{{grid-template-columns:1fr}}}}</style></head>
<body><main><h1>{html.escape(title)}</h1><p class="sub">Generated by pmkit from {len(rows)} deals.</p><div class="kpis">{k}</div>
<div class="grid"><div class="card"><h2>Win rate by segment</h2>{seg}</div><div class="card"><h2>Win rate by competitor</h2>{comp}</div>
<div class="card"><h2>Why we lose</h2>{rea}</div><div class="card"><h2>What this says</h2><ul>{ins}</ul></div></div></main></body></html>"""
